import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ModalProvider } from '~/components/providers/modal-provider'
import QueryProvider from '~/components/providers/query-provider'
import { SocketProvider } from '~/components/providers/socket-provider'
import { ThemeProvider } from '~/components/providers/theme-provider'
import { Toaster } from '~/components/ui/sonner'
import { cn } from '~/lib/utils'
import '~/styles/globals.css'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Discord 2',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, 'bg-white dark:bg-[#313338]')}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="_discord_theme"
          >
            <Toaster />
            <SocketProvider>
              <ModalProvider />
              <QueryProvider>{children}</QueryProvider>
            </SocketProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
